PROJECT_ARGS=LANGUAGE=cpp TARGET_TYPE=lib COMPILER=g++ LIB_NAME=libcmath.a LIB_TYPE=static HEADER_FOLDERS='inc inc/calc' SOURCE_FOLDERS='src/calc' -f third_party/make-tmpl/Makefile

lib:
	make $(PROJECT_ARGS)

info:
	make info $(PROJECT_ARGS)

clean:
	make clean $(PROJECT_ARGS)
