ARGS=LIB_NAME=libcmath.a  LIB_TYPE=static HEADER_FOLDERS='inc inc/calc' SOURCE_ROOT_FOLDER= SOURCE_FOLDERS='src/calc'

lib:
	make $(ARGS) -f third_party/make-tmpl/Makefile

info:
	make info $(ARGS) -f third_party/make-tmpl/Makefile

clean:
	make clean $(ARGS) -f third_party/make-tmpl/Makefile